### ISSUE TITLE
How can we get the size of a process' mailbox

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#105]
Following on from issue #89 - it's pretty touch to implement this properly because if the process in question is stuck in a blocking receive, you'll block the caller until the `MVar` containing the *arrived* messages put back. Of course it's very easy to deadlock in that kind of situation too.

How can we go about making this state readable without introducing lots of contention or worse affecting the semantics? Would it make sense to keep an `IORef Int` in the `CQueue` state? After all, we would presumably only *write* to that inside of `dequeue` and **that** routine acts like a critical section (because it calls `takeMVar` prior to doing anything).

**Comment by qnikst** [comment]
This was done #176.
