### ISSUE TITLE
network-transport-inmemory test failures

### ISSUE THREAD

**Issue by ericbmerritt** [haskell-distributed/distributed-process#108]
In the current HEAD network-transport-inmemory tests fail. Attached is the output. 

This is using haskell platform 2012.04.0.0 on Mac OSX 10.8.2. 

Test suite TestInMemory: RUNNING...
Running "PingPong": ok
Running "EndPoints": ok
Running "Connections": ok
Running "CloseOneConnection": ok
Running "CloseOneDirection": ok
Running "CloseReopen": ok
Running "ParallelConnects": ok
Running "SendAfterClose": failed (exception: user error (Pattern match failure in do expression at src/Network/Transport/Tests.hs:413:7-40)
Trace:
0       Left (TransportError SendFailed "Connection closed")
1       "15"
)
Running "Crossing": ok
Running "CloseTwice": ok
Running "ConnectToSelf": ok
Running "ConnectToSelfTwice": ok
Running "CloseSelf": failed (exception: user error (Pattern match failure in do expression at src/Network/Transport/Tests.hs:560:3-36)
Trace:
0       Left (TransportError SendFailed "Connection closed")
)
Running "CloseEndPoint": failed (exception: user error (closeEndPoint not implemented)
Trace:
0       "23"
)
Running "CloseTransport": failed (timeout)
Running "ConnectClosedEndPoint": failed (exception: user error (closeEndPoint not implemented))
Running "ExceptionOnReceive": failed (exception: user error (closeEndPoint not implemented))
Running "SendException": failed (exception: user error (Pattern match failure in do expression at src/Network/Transport/Tests.hs:813:3-36)
Trace:
0       ConnectionOpened 1 ReliableOrdered 0
)
Running "Kill": TestInMemory: thread blocked indefinitely in an MVar operation
Test suite TestInMemory: FAIL
Test suite logged to: dist/test/network-transport-inmemory-0.3.0-TestInMemory.log

**Comment by qnikst** [comment]
Fixed in https://github.com/haskell-distributed/network-transport-inmemory/issues/4 . Multicast support is not ready yet. Will be merged soon.
