### ISSUE TITLE
Network.Transport.Chan is named incorrectly

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#125]
The project name is right: `network-transport-inmemory`. To use `Chan` as the module is to let an implementation detail leak into the public API. I suggest we move to either

* `Network.Transport.Numa`
* `Network.Transport.Memory`
* `Network.Transport.InMemory`

We will pick one of these (probably `Memory` IMO) for the next major release.

**Comment by qnikst** [comment]
Issue was moved to https://github.com/haskell-distributed/network-transport-inmemory/issues/4
