### ISSUE TITLE
[DP-95] Expose ability to set up bi-directional links

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/distributed-process#214]
[Imported from JIRA. Reported by Gleb Peregud @gleber)  as [DP-95](https://cloud-haskell.atlassian.net/browse/DP-95) on 2014-06-08 11:23:28]
I am working on Erlang interpreter/VM in Haskell using CloudHaskell. One of erlang's BIFs is link/1, which creates a bi-directional link between processes. In Cloud Haskell links are unidirectional. The only way to implement bi-directional linking, I found, was to expose Control.Distributed.Process.Internal.Primitives (sendCtlMsg) in distributed-process.cabal and then to do the following:

https://github.com/gleber/erlhask/blob/master/src/Language/Erlang/Bif/Erlang.hs#L98

This is, obviously, not a nice solution. Do you think it is possible to add a new API call to set up bi-directional link and appropriate unlink? It will need a proper documentation which explains it is just a composition of two uni-directional links.

Thoughts?

If you think such API can have place in external APIs, I will gladly send you a pull request with this.

**Comment by hyperthunk** [comment]
We discussed this in depth on Jira before the issue migration back to github. I think it would need the to rely on the Management API to work, and we should probably put it (if we implement it at all) in distributed-process-extras. So I'm going to close this and we can re-open if Gleb comes back and asks for it again.
