### ISSUE TITLE
[DP-70] Provide MonadTrans-esque support for Process

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/distributed-process#225]
[Imported from JIRA. Reported by Tim Watson [Administrator] @hyperthunk)  as [DP-70](https://cloud-haskell.atlassian.net/browse/DP-70) on 2013-03-04 13:57:43]
Make it possible to `lift' actions from other contexts (besides IO). Edsko suggests (on IRC) that you would have to generalize Process to ProcessT, and reintroduce Process as ProcessT IO (or something like that).

**Comment by jeremyjh** [comment]
If anyone is looking for this kind of functionality, I've published a separate library on Hackage which provides pretty much everything looked for in this.

https://github.com/jeremyjh/distributed-process-lifted
http://hackage.haskell.org/package/distributed-process-lifted

**Comment by hyperthunk** [comment]
Shall we close this issue then?

**Comment by jeremyjh** [comment]
I would say yes and if there are use cases I don't solve for that we log
those as issues on the lifted project.

**Comment by hyperthunk** [comment]
Agree, I'll close this when I'm not on a mobile phone. :)
