### ISSUE TITLE
Check that MxUnregistered event is produced whenerver Process leaves registry

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/distributed-process#240]
PR #212  relies on MxUnregistered event to be produced when process leaves registry (the case on reregister is included),

but it seems that currently it's not a case: https://github.com/haskell-distributed/distributed-process/blob/master/src/Control/Distributed/Process/Node.hs#L857-L874

we need to validate requirement and add tests that guarantee that requirement is addressed.

**Comment by hyperthunk** [comment]
@qnikst can you confirm why you don't think the event is generated, that diff/line ref is out of date..

**Comment by qnikst** [comment]
Hm.. unfortunatelly I don't remember my concern. And how I see that there is an MxUnregister in local case.. I think this issue could be closed.

**Comment by hyperthunk** [comment]
Well this was a blocker for #184, so do we want to verify that PR/issue first? Because I think there *are* some guarantees in the management api, viz what I've said in #241.

**Comment by hyperthunk** [comment]
Shall we close this now, or do we still feel there's a problem with management events not getting generated?

**Comment by qnikst** [comment]
We can close it now, everything is fine.

**Comment by hyperthunk** [comment]
Awesome, thanks!
