### ISSUE TITLE
Concurrent calls to call get queued up for some reason

### ISSUE THREAD

**Issue by nh2** [haskell-distributed/distributed-process#245]
(Copied from https://cloud-haskell.atlassian.net/browse/DP-114)

You can find a complete example at https://gist.github.com/nh2/f36ea9208c6070adc129

I tested this with `distributed-process-0.5.3`.

When running e.g. 5 `call`s in parallel, often only 2-3 of them actually get started on the remote side; the other ones seem to get queued up somewhere. As soon as the first one completes on the remote side, the queued up ones start executing.

You observe that that in the minimal example that I attached. There I'm `call`ing `sleep 3` up to `sleep 8` on the remote side. In my last run, only a `sleep 3 called ...` message appeared, then after 3 seconds all the other `sleep N called ...` messages appeared.

This problem doesn't usually show up when the inputs to call are very small, but if you make them bigger, e.g. a 100MB lazy ByteString, then you can observe the problem pretty much every time. My attached example does that.

Please let me know whether you can reproduce.

**Comment by qnikst** [comment]
This is not great example as it's not legal to lift `forkIO` to Process monad [1] (and use methods living in `Process` monad there). Reason is that many haskell thread shares same Pid, mailbox, etc. with all sort of possible races and problems (killing haskell thread associated with Pid, will not lead to the death of other threads associated with the same Pid).  This doesn't mean that `d-p` is totally correct here, and I'll try to investigate, but consider not using `forkIO` using `control-monad` in such mages.

[1] https://gist.github.com/nh2/f36ea9208c6070adc129#file-cloudhaskell-call-queued-messages-problem-hs-L53

P.S. basically same is true for all Monads with the state implicitly depending on the thread id, another notable example is `RegionT` and `ResourceT` monads that have special hacks to workaround this problem.

**Comment by qnikst** [comment]
@nh2 I've changed using `control-monad`, to basic C-H primitives `spawnLocal` instead of `forkIO` and `liftIO` for `IO` operations, and everything works fine for me. If you still unsure that `call` is reliable here, could you give an idea how test will be rewritten using basic C-H primitives.

If you really need `control-monad` instance, and for some reason you want to be able to use `forkIO` or analogue there, we could discuss that, but I think that the only safe way will be introducing new primitive (basically exporting `forkProcess` from d-p internals).

Are you ok, with such resolution? Haven't I miss anything?

**Comment by qnikst** [comment]
link to my version: https://gist.github.com/qnikst/90545975fb758e9ee8b0

**Comment by mboes** [comment]
I'd say CH intentionally does not define a MonadBaseIO instance for good reason: you can otherwise end up with multiple threads sharing the same identity.

**Comment by mboes** [comment]
@qnikst confirm close?

**Comment by nh2** [comment]
> This is not great example as it's not legal to lift forkIO to Process monad

> I'd say CH intentionally does not define a MonadBaseIO instance for good reason: you can otherwise end up with multiple threads sharing the same identity.

Ah, that makes sense. So far I thought the instance was legal, but not included to not introduce a dependency of `distributed-procress` to `monad-control`, and that https://hackage.haskell.org/package/distributed-process-monad-control was a somewhat official thing (from which I copied the instance).

Thanks for the clarification!

**Comment by mboes** [comment]
I think `distributed-process-control` should be deprecated. Or at least include a big fat warning at the top about when it is dangerous to use it (i.e. whatever you do don't `forkIO`). @jeremyjh what do you think?

**Comment by jeremyjh** [comment]
People are going to use it - the point of the package is to avoid conflicting orphans. I agree it can use the warning - I will add that.
