### ISSUE TITLE
Tracing is broken

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#265]
Tracing for named send, unreliable send, and monitoring appears to be either missing or has been stripped out accidentally in previous commits. I'll look at putting this back in.

**Comment by facundominguez** [comment]
Not sure if it is meant to be fixed here.

Tracing received messages currently produces a loop, which I hope to fix [here](https://github.com/haskell-distributed/distributed-process/commit/bf0bea796c5beda81a6347fe86663a7585d135f7).
It is not very elegant but it should work while something better is implemented.

I will make a PR after I write some tests.

**Comment by hyperthunk** [comment]
That code makes sense, as does the bug. Silly mistake on my part.. Thanks for the spot, and fix!

**Comment by hyperthunk** [comment]
I'm just starting to cook up a PR for this..

**Comment by hyperthunk** [comment]
I am working on proving the things that we're saying in #241
