### ISSUE TITLE
Confusion about stack.yaml and network-transport-tcp version required

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#277]
I'm pretty confused by this right now. It seems that distributed-process-tests-0.4.5 requires >= network-transport-tcp-0.5, but the stack.yaml for distributed-process states that it wants 0.4.2. This causes `stack build` to fail for me:

```bash
--  Failure when adding dependencies:
      network-transport-tcp: needed (>=0.5 && <0.6), latest is 0.5.1, but 0.4.2 found
    needed for package: distributed-process-tests-0.4.5
```

I fixed it locally by modding stack.yaml, but not sure that's the right thing to do here? And why isn't this failing on travis in that case!?

```
t4@malachi:distributed-process $ git diff stack.yaml
diff --git a/stack.yaml b/stack.yaml
index ed1e7c5..3312b2d 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -4,7 +4,7 @@ packages:
 - distributed-process-tests/
 extra-deps:
 - distributed-static-0.3.2.0
-- network-transport-tcp-0.4.2
+- network-transport-tcp-0.5.1
 - network-transport-inmemory-0.5.0
 - rank1dynamic-0.3.1.0
 - rematch-0.2.0.0
```

**Comment by facundominguez** [comment]
When testing d-p, I am using the cloud-haskell umbrella. Travis for d-p uses cabal. I think that's why the problem in stack.yaml must have slipped.

**Comment by facundominguez** [comment]
If we are splitting CH perhaps I could drop the umbrella and use d-p/stack.yaml and have travis use it. @mboes?

**Comment by mboes** [comment]
Yes, sounds like the right way forward to me. Note that the extra-deps shouldn't be needed anymore. They're all in Stackage now.

**Comment by hyperthunk** [comment]
+1

**Comment by hyperthunk** [comment]
I'm going to close this issue, unless we want to use it to track the extra-deps fix that we want?

**Comment by facundominguez** [comment]
Fixed in f468f06, I hope.

**Comment by qnikst** [comment]
Is anything left in this task, @hyperthunk ?

**Comment by hyperthunk** [comment]
I don't think so no, closing.
