### ISSUE TITLE
Consistent Test Failures (USend)

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#278]
OS-X El-Capitan, ghcformac v7.10.{2,3}, latest stack:

```
USend: [Failed]
ERROR: thread blocked indefinitely in an MVar operation
```

I get this building HEAD, by running `stack test` in the distributed-process directory (after fiddling with the required version of n-t-tcp, as per issue #277).

This failure *only* happens with TestCHInMemory, TestCHInTCP blocks indefinitely. Naturally this makes it quite tricky to test changes.... :/

I'll try clearing out all my stack folders (local and $HOME/.stack) and see if it makes any difference, but I'm under the impression stack isolates things properly so I doubt that'll help....

**Comment by facundominguez** [comment]
I cannot debug this on OSX. Perhaps you could print in the console the exceptions which are killing the threads which are supposed to fill the MVar in question.

**Comment by hyperthunk** [comment]
This may have been a red herring, since I was running the stack commands in the local directory, instead of in the umbrella. Let me look into it a bit further and get back to you.

**Comment by hyperthunk** [comment]
Okay scratch this, I can test successfully using HEAD, so this is not an issue. Sorry for the noise.
