### ISSUE TITLE
Broken links in tutorial

### ISSUE THREAD

**Issue by ocramz** [haskell-distributed/distributed-process#298]
The .hs files referenced in https://haskell-distributed.github.io/tutorials/tutorial-NT2.html (`tutorial-client.hs` and `tutorial-server.hs`) give a 404.

**Comment by qnikst** [comment]
I can't reproduce problem. I've tried to follow the link and both files downloaded successfully for me, 
Here are links:

https://haskell-distributed.github.io/static/tutorial/tutorial-server.hs
https://haskell-distributed.github.io/static/tutorial/tutorial-client.hs

I'm uploading files here in zip archive in case if links above still doesn't work.

[files.zip](https://github.com/haskell-distributed/distributed-process/files/516865/files.zip)
