### ISSUE TITLE
Polymorphic expect

### ISSUE THREAD

**Issue by edsko** [haskell-distributed/distributed-process#30]
With the standard Cloud Haskell primitives it is impossible to write processes such as a proxy; for instance, we cannot write something like

```Haskell
proxy :: Process ()
proxy = forever $ do
  msg <- expect
  send someOtherProcess msg
```

which forwards messages _of any type_. The most recent version of Cloud Haskell supports `matchAny`, with which the above process can be written as

```Haskell
proxy :: Process ()
proxy = forever $ do
  msg <- receiveWait [ matchAny return ]
  forward someOtherProcess msg
```

but we still cannot write something like

```Haskell
proxy :: Process ()
proxy = forever $ do
  (destination, msg) <- expect
  send destination msg
```

For this we would need an alternative `Binary` encoding (maybe even something like [protocol buffers](https://developers.google.com/protocol-buffers/)?) which would allow us to decode a message into a pair of messages without knowing the types of the pair components, i.e., something like

```Haskell
decodePair :: ByteString -> (ByteString, ByteString)
```

**Comment by qnikst** [comment]
@hyperthunk As far as I understand everything in this task was merged and published? can we close it?

**Comment by hyperthunk** [comment]
Yes, we can close. Sorry for the massive delay...
