### ISSUE TITLE
Would like to do without Template Haskell

### ISSUE THREAD

**Issue by ijt** [haskell-distributed/distributed-process#300]
I'm interested in having distributed-process without Template Haskell, but I'm new to this. How much work would be involved in removing TH, or is it so important to this project that it wouldn't even make sense?

**Comment by qnikst** [comment]
Having `distributed-process` without Template Haskell is as simple as configure it without `th` flag. That can be done depending on tools you use by either:
  * if you use `stack`, in stack.yaml add:
```
flags:
  distributed-process:
    th: false
```
  * if you use pure cabal-install:
```
cabal configure -f-th
```
   * or if you use cabal with .project file support
```
constraints: distributed-process -th
```

Distributed-process uses almost no TH, all template haskell code is about using it for writing remote tables and constructing static functions https://hackage.haskell.org/package/distributed-process-0.6.6/docs/Control-Distributed-Process-Internal-Closure-TH.html so if you can make it by hands, then TH may be omitted.

**Comment by qnikst** [comment]
And I should add that if you want to build remote-tables explicitly you will be interested in functions provided by [Control.Distributed.Process.Internal.Closure.Explicit](http://hackage.haskell.org/package/distributed-process-0.6.6/docs/Control-Distributed-Process-Internal-Closure-Explicit.html) module.

**Comment by qnikst** [comment]
The same API is reexported in public modules: https://hackage.haskell.org/package/distributed-process-0.6.6/docs/Control-Distributed-Process-Closure.html#g:4

**Comment by ijt** [comment]
Oh, that's good to know.

To answer your question, the style guide where I work doesn't allow the use of Template Haskell.
