### ISSUE TITLE
Document how to resolve name on remote node

### ISSUE THREAD

**Issue by teh** [haskell-distributed/distributed-process#305]
I'm struggling to understand what I need to do in order to resolve a remote name. I have two different binaries (server and client), and no matter what I do, a resolution like the following:

```
        let addr = DP.NodeId (DP.EndPointAddress "127.0.0.1:8081:0")
        res <- DP.resolveOrDie (addr, "http"::String) "nope"
```

breaks with this trace message on the server:

```
Sun Feb  5 16:27:30 UTC 2017 [trace] MxProcessDied pid://127.0.0.1:8081:0:11 (DiedException "user error (Error: Could not resolve closure: Invalid static label 'Control.Distributed.Process.Extras.Internal.Types.whereis')")
```

I trawled all the docs and repositories I can find but I can't see an explicit `__remoteTable` setup for `whereis`. I'm unclear on whether I need to provide this, or whether this should work and I am doing something wrong.

Anyway, any pointers or updates to docs would be greatly appreciated. Thanks for the amazing work!

**Comment by hyperthunk** [comment]
Both binaries need the same table of type reps, so although your Main.hs can differ, you need to ensure that you've essentially got the same binary (or at least, that you've got exactly the same remote table) for both client and server.

The way remote tables are set up is that you compose them. distributed-process-extras exports its own remote table, which needs to be passed in with the initRemoteTable from distributed-process, as do other remote tables if you're making use of the static labels they export. See [here](https://github.com/haskell-distributed/distributed-process-extras/blob/master/tests/TestPrimitives.hs#L142) for example.

**Comment by teh** [comment]
Ah great, thanks! That `__remoteTable` you linked was indeed all that was missing.

I understand the part about type representations having to be the same but that took me a while to figure out as well. Maybe that's something else that could be mentioned in a more central place if you are updating the docs?

I wonder what guarantees GHC gives for `Fingerprint`. I'll have to read up on the code generation.

**Comment by qnikst** [comment]
Not much, ideally you need to have exact version of the dependencies (including hashes). This d-p is really working if you have same executable or executables built in the same library.
Especially if you use static pointers instead of the remote tables.
