### ISSUE TITLE
build failure w/ base-4.7 & base-4.6

### ISSUE THREAD

**Issue by hvr** [haskell-distributed/distributed-process#317]
The cabal file advertises support for `base >= 4.6 && < 5`, however GHC disagrees:

![](https://user-images.githubusercontent.com/285533/44623057-a54b4f80-a8c5-11e8-89e8-aa6be49461d1.png)

I've already revised the 3 affected releases, so there's no immediate need for any action on your part; however please take this into account for future releases

- https://hackage.haskell.org/package/distributed-process-0.7.2/revisions/
- https://hackage.haskell.org/package/distributed-process-0.7.3/revisions/
- https://hackage.haskell.org/package/distributed-process-0.7.4/revisions/

**Comment by hyperthunk** [comment]
Folks... What do we think about dropping advised support for those versions? I personally have no interest in maintaining compatibility with GHC 7.x.

**Comment by qnikst** [comment]
Yes, as usual, 3 version support, 7.10 may survive until it compiles but no longer, for the older versions we should just do not allow that.

**Comment by hyperthunk** [comment]
Okay, I'm going to update all the library ecosystem that way then. Can I leave you to do this for distributed-process/static, and close this bug?

**Comment by LaurentRDC** [comment]
Due to limited maintenance resources, supported GHC versions are currently 8.10.7 - 9.10.1 (base 4.14 - 4.20). This issue is no longer relevant
