### ISSUE TITLE
Rethink the build... 

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#324]
So, I tweaked the build and added support for 7.10, 8.0.x, 8.2.2, and 8.6.2...

This is good, from a coverage perspective, but the build took almost an hour to complete... Neither github nor Travis seem to offer a simple solution to this. 

One option would be to mirror the repository in gitlab, and configure a CI pipeline there for the regression builds and latest stack nightly, leaving just the one simple build for a stable lts (such as 12.xx) running on Travis for check in.

Another alternative would be to establish an lts branch of our own, and only merge pre releases to it, but personally I like the idea that I can see bugs or build issues crop up in regression builds for each check in. I just don't like that it takes an hour for a PR to verify!

**Comment by facundominguez** [comment]
We have two travis builds per PR, perhaps we could set things up to have only one build per PR? This would bring build times to 25 minutes IIUC.

**Comment by LaurentRDC** [comment]
With Github Actions, builds are now taking less than 8 minutes, since all builds occur in parallel. Seems good enough
