### ISSUE TITLE
The remote registry test case is far too racy

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#333]
I'm not sure why we're seeing this happen more consistently now, but I'll investigate and fix

**Comment by hyperthunk** [comment]
It seems something was really broken for these failures to occur...

The first is against ghc-8.4.4, in TestCHInTCP, and [here is the build log](https://travis-ci.org/haskell-distributed/distributed-process/jobs/458999359). Note:
```
  RegistryMonitoring: [Failed]
expected (Just pid)
```

Which means the following code failed:

```haskell
  runProcess node2 $ do
    register regName pid
    res <- whereis regName
    liftIO $ do
      putMVar waitH ()
      assertBool "expected (Just pid)" $ res == (Just pid)
```

I *really* cannot see how this failed without us generating a `ProcessRegistrationException` in the `register` call... :/

The next failure was a general test failure, logged [here](https://travis-ci.org/haskell-distributed/distributed-process/jobs/458999357) against ghc-7.10.3, in TestCHInMemory

```
RegistryMonitoring: [Failed]
expected Nothing, but process still registered)
```

This means we waited and saw the the name was registered, told the registered pid to exit (by writing to the mvar it was waiting on), waited four seconds, then executed a `whereIsRemoteAsync` call and waited for a `WhereIsReply` with a twenty second timeout, then ran *another* call to `whereis` (the local version, as the registration took place on this node), and we still had a process registered in our local registry...

What I'm reading from that second failure, is that either (a) despite waiting for 20 seconds to see the right update, the network transport layer had not notified our node yet that the remote process has died, or (b) our cleanup code isn't covering some odd edge case.

**Comment by hyperthunk** [comment]
Sadly this test failures are not something I've seen before (since the test code was added), cannot be reproduced locally - I've been running the test suite in a loop waiting for failures under OSX High Sierra on an Intel Core i5 (dual core) machine, and on an identical machine running docker, using the same Ubuntu Trusty image that travis uses.  So far 7 hours of continuous testing on both platforms and I've not been able to reproduce...

**Comment by hyperthunk** [comment]
Unfortunately, adding a monitor to the test case (to ensure the remote pid is down) would break the invariants upon which the test case is predicated, since we're trying to assert that we handle the deaths of remote processes that are registered locally without the requirement for explicit monitoring.

What I *can* do is run a monitoring agent on the remote node, and validate there that we have indeed seen the death of that process. It would remove the already slim possibility of a race in the test case, so I might do that, but it's hard to know whether it's helped or not given the low probability of reproducing this failure in the first place.

I will make the changes and commit to master, then consider this issue resolved unless we see the failure(s) crop up again in CI.

**Comment by hyperthunk** [comment]
Managed to reproduce locally, on an Ubuntu trusty docker image. Consider the build log:

```
distributed-process-tests-0.4.11: test (suite: TestCHInMemory, args: -t !Flaky)

Basic features:
  Ping: [OK]
  Math: [OK]
  Timeout: [OK]
  Timeout0: [OK]
  SendToTerminated: [OK]
  TypedChannnels: [OK]
  Terminate: [OK]
  RegistryRemoteProcess: [OK]
  RemoteRegistry: [OK]
  RemoteRegistryRemoteProcess: [OK]
  SpawnLocal: [OK]
  SpawnAsyncStrictness: [OK]
  HandleMessageIf: [OK]
  MatchAny: [OK]
  MatchAnyHandle: [OK]
  MatchAnyNoHandle: [OK]
  MatchAnyIf: [OK]
  MatchMessageUnwrap: [OK]
  ReceiveChanTimeout: [OK]
  ReceiveChanFeatures: [OK]
  ChanLifecycle: [OK]
  KillLocal: [OK]
  KillRemote: [OK]
  Die: [OK]
  PrettyExit: [OK]
  CatchesExit: [OK]
  Catches: [OK]
  MaskRestoreScope: [OK]
  ExitLocal: [OK]
  ExitRemote: [OK]
  RegistryMonitoring: [Failed]
expected Nothing, but got pid://47:8
  TextCallLocal: [OK]
  TestUnsafeSend: [OK]
  TestUnsafeUSend: [OK]
  TestUnsafeNSend: [OK]
  TestUnsafeNSendRemote: [OK]
  TestUnsafeSendChan: [OK]
  USend: [OK]
  UForward: [OK]
Monitoring and Linking:
  MonitorNormalTermination: [OK]
  MonitorAbnormalTermination: [OK]
  MonitorLocalDeadProcess: [OK]
  MonitorRemoteDeadProcess: [OK]
  MonitorDisconnect: [OK]
  LinkUnreachable: [OK]
  LinkNormalTermination: [OK]
  LinkAbnormalTermination: [OK]
  LinkLocalDeadProcess: [OK]
  LinkRemoteDeadProcess: [OK]
  LinkDisconnect: [OK]
  UnmonitorNormalTermination: [OK]
  UnmonitorAbnormalTermination: [OK]
  UnmonitorDisconnect: [OK]
  UnlinkNormalTermination: [OK]
  UnlinkAbnormalTermination: [OK]
  UnlinkDisconnect: [OK]
  MonitorNode: [OK]
  MonitorLiveNode: [OK]
  MonitorChannel: [OK]

         Test Cases   Total
 Passed  58           58
 Failed  1            1
 Total   59           59

distributed-process-tests-0.4.11: Test suite TestCHInMemory failed
Test suite failure for package distributed-process-tests-0.4.11
    TestCHInMemory:  exited with: ExitFailure 1
Logs printed to console
```

Now consider the diff, since I added some logging statements:

```diff
diff --git a/distributed-process-tests/src/Control/Distributed/Process/Tests/CH.hs b/distributed-process-tests/src/Control/Distributed/Process/Tests/CH.hs
index 0d16cc1..44b290f 100644
--- a/distributed-process-tests/src/Control/Distributed/Process/Tests/CH.hs
+++ b/distributed-process-tests/src/Control/Distributed/Process/Tests/CH.hs
@@ -1560,7 +1560,9 @@ testRegistryMonitoring TestTransport{..} = do

   let nid = localNodeId node2
   pid <- forkProcess node1 $ do
-    getSelfPid >>= runUntilRegistered nid
+    self <- getSelfPid
+    runUntilRegistered nid self
+    say $ regName ++ " registered to " ++ show self
     liftIO $ takeMVar waitH

   runProcess node2 $ do
@@ -1594,7 +1596,9 @@ testRegistryMonitoring TestTransport{..} = do
   regHere <- newEmptyMVar
   runProcess node2 $ whereis regName >>= liftIO . putMVar regHere
   res <- takeMVar regHere
-  assertBool "expected Nothing, but process still registered" (res == Nothing)
+  case res of
+    Nothing  -> return ()
+    Just pid -> assertBool ("expected Nothing, but got " ++ show pid) False

   where
     runUntilRegistered nid us = do
@@ -1607,7 +1611,7 @@ testRegistryMonitoring TestTransport{..} = do
     delayUntilMaybeUnregistered nid p = do
       whereisRemoteAsync nid regName
       receiveTimeout 20000000 {- 20 sec delay -} [
-          matchIf (\(WhereIsReply n p) -> n == regName && p == Nothing)
+          matchIf (\(WhereIsReply n p) -> n == regName && isNothing p)
                   (const $ return ())
         ]
       return ()
diff --git a/untilfail b/untilfail
index 8c4e406..3010939 100755
--- a/untilfail
+++ b/untilfail
@@ -1,3 +1,4 @@
 #!/bin/bash

-while $@; do :; done
+CMD="./foo $@"
+while $CMD; do echo "test passed"; done
``` 

It seems to me, since we never saw the side effect of that `say $ regName ++ " registered to " ++ show self` expression printing to the console, that either `runUntilRegistered` is broken, *or* - and this is my suspicion - because both nodes are running inside the same program, the scheduler does not schedule the threads dealing with node1 fast enough for node2 to see the side effects before timing out.

I think this is a general failing in a number of these test cases. We should probably spawn a separate OS process to host the remote node and use spawn to spin up the remote test processes on a truly remote node. Quite how we do this isn't clear to me yet, especially as we need to avoid leaving zombie processes around, but I'll have a think about how to fix this...

**Comment by hyperthunk** [comment]
We should also work with https://github.com/advancedtelematic/quickcheck-state-machine-distributed to add deterministic scheduling for some of our test cases...

**Comment by facundominguez** [comment]
> because both nodes are running inside the same program, the scheduler does not schedule the threads dealing with node1 fast enough for node2 to see the side effects before timing out.

One possibility is that `delayUntilMaybeUnregistered` does not get on the first attempt the reponse that it expects. That is the process is still registered and it gets the pid, but the `matchIf` disregards that message and keeps on waiting until the time out expires.

It looks as if the test requires `delayUntilMaybeUnregistered` to poll the registry until the process is eventually unregistered.

In any case, I wouldn't consider working with other UNIX processes yet. The test should be made to work unsurprisingly in the single-process/multiple-node case.

**Comment by hyperthunk** [comment]
Agreed. I'll adjust the test case for the local approach, and keep the splitting to separate OS processes as a separate patch set

**Comment by hyperthunk** [comment]
@facundominguez I should point out though, I introduced that timeout because the test case kept deadlocking in CI and getting cancelled by travis...

**Comment by hyperthunk** [comment]
hmmm - I wonder if we can stimulate that to stop happening by increasing the traffic between the nodes... It would be rather bad if that were the case, but I might experiment a bit. As always, the challenge here is in triggering the issue.. It took me 36 hours loop testing the whole suite in a docker container to get this to fail at home..

**Comment by hyperthunk** [comment]
I believe we have resolved this for the "2 nodes hosted in a single RTS" case. I am closing the issue for now.
