### ISSUE TITLE
New compatability release

### ISSUE THREAD

**Issue by alexbiehl** [haskell-distributed/distributed-process#343]
I see MonadFail compatibility has been solved on master. Could you cut a new release and upload to hackage?

**Comment by bgamari** [comment]
@facundominguez, would it be helpful to solicit help maintaining this package? It's a great implementation of a very useful set of ideas; it would be a shame if users were unable to benefit from the package due to lack of a release.

**Comment by facundominguez** [comment]
> would it be helpful to solicit help maintaining this package?

Possibly. Note that the current maintainer is Tim Watson, though. Let me know if I can help setting up a new volunteer.

**Comment by joelmccracken** [comment]
Is it possible for me to make to get access to do a release?

**Comment by LaurentRDC** [comment]
[Version 0.7.5](https://hackage.haskell.org/package/distributed-process-0.7.5) was released yesterday
