### ISSUE TITLE
maintainance issue w.r.t. STM dependency & GHC version compatibility 

### ISSUE THREAD

**Issue by justchilling** [haskell-distributed/distributed-process#348]
Software Transactional Memory is part of GHC boot libraries and is shipped together, coupled with the compiler version. 
( i.e. I cannot install another version of it, other than what comes with GHC)
https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/version-history
https://wiki.haskell.org/Library_submissions#The_Libraries

distributed-process has hard dependency (==) on stm 2.4.* which is only available with GHC 8.4.* 
from GHC 8.6 onwards, stm 2.5 is shipped. So now to use distributed-process, I'd have to downgrade my GHC, which is problematic. 

```
rejecting: distributed-process-0.7.4 (conflict:
stm==2.5.0.0/installed-2.5.0.0, distributed-process => stm>=2.4 && <2.5)
```

**Comment by LaurentRDC** [comment]
This has been remedied; dependency bounds for the past two versions of `distributed-process` is `stm >= 2.4 && <2.6`.
