### ISSUE TITLE
broken link in repo description

### ISSUE THREAD

**Issue by joprice** [haskell-distributed/distributed-process#349]
clicking the link in the repo's description leads to a 404, that recommends trying https://haskell-distributed.github.io/ instead. That site seems to be the correct url.

**Comment by joprice** [comment]
I see it was also incorrect in the readme, which I hadn't noticed, but I was actually referring to the one in the repo's description, on the right side of the page. That is not updatable via pr, but is editable by owners.

**Comment by facundominguez** [comment]
Hey, I fixed the link in the description. I'm not maintaining d-p anymore, but having the permissions to fix the link, why not? :)

**Comment by joelmccracken** [comment]
Ahhhh got it. Misunderstood. Thank you @joprice and @facundominguez
