### ISSUE TITLE
Evaluate CI providers

### ISSUE THREAD

**Issue by joelmccracken** [haskell-distributed/distributed-process#354]
What do we care about with this? I don't love GitHub, but it seems like github actions are very commonly used.

Any other projects we can steal ideas from for how they do it?

This isn't really specific to `distributed-process`, but this seems to be the "main" repository for Distributed Haskell. 

See also #353

**Comment by joelmccracken** [comment]
https://circleci.com/open-source/

**Comment by LaurentRDC** [comment]
We have been using GitHub CI and it works well.
