### ISSUE TITLE
Remove rematch dependency in distributed-process-tests

### ISSUE THREAD

**Issue by davidsd** [haskell-distributed/distributed-process#363]
The `rematch` library appears to be dead -- it would be useful to remove it as a dependency of `distributed-process-tests`. (And also from other packages if it's used elsewhere...)

**Comment by LaurentRDC** [comment]
Completed in [1003248](https://github.com/haskell-distributed/distributed-process/commit/1003248d41e0dcd6519ae9c68dbedaf35a332eec)
