### ISSUE TITLE
Build failure with ghc-9.2.4 `Expecting one more argument to ‘TyVarBndr’`

### ISSUE THREAD

**Issue by TristanCacqueray** [haskell-distributed/distributed-process#366]
It seems like distributed-process is not buildable with ghc-9.2 because of this error:

```
src/Control/Distributed/Process/Internal/Closure/TH.hs:225:18: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the type signature:
        monomorphize :: [TyVarBndr] -> Type -> Q Type
    |
225 | monomorphize :: [TyVarBndr] -> Type -> Q Type
    |                  ^^^^^^^^^
```

Only this module is affected, is there some CPP magic we can use to fix that error?

**Comment by matt2718** [comment]
Submitted a fix:
https://github.com/haskell-distributed/distributed-process/pull/367

**Comment by davidsd** [comment]
FIxed with https://github.com/haskell-distributed/distributed-process/pull/370
