### ISSUE TITLE
Support `closeConnectionTo`

### ISSUE THREAD

**Issue by edsko** [haskell-distributed/distributed-process#37]
which closes the entire "bundle" of (outgoing _and_ incoming) connections to another endpoint. Basically, "disconnect completely from this other endpoint" (a "heavyweight disconnect"). 

Once this is implemented we can resolve a TODO in `Control.Distributed.Process.Node`.

**Comment by mboes** [comment]
This issue was moved to haskell-distributed/network-transport#25
