### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by LaurentRDC** [haskell-distributed/distributed-process#378]
Hello,

Would it be possible to upload a new release to Hackage?

I am looking to bring many distributed-process-* libraries up to GHC 9.8. Recent PRs (#376 and #377) mean that `distributed-process` can be compiled with GHC 9.8, but other libraries (e.g. `distributed-process-simplelocalnet`) depend on `distributed-process`.

Thank you for your help!

**Comment by LaurentRDC** [comment]
For example, updates to `distributed-process-simplelocalnet` may require a new release of `distributed-pricess`: https://github.com/haskell-distributed/distributed-process-simplelocalnet/pull/26

**Comment by davidsd** [comment]
I am working on this right now. I am having to update all of the dependencies of distributed-process along the way. Currently, I am stuck because I do not have upload rights to `network-transport-inmemory` on hackage. @facundominguez could you grant me access?

**Comment by facundominguez** [comment]
:+1: Done.

**Comment by davidsd** [comment]
The new release is on hackage!

**Comment by LaurentRDC** [comment]
Thank you!
