### ISSUE TITLE
Add LaurentRDC to the hackage maintainers list

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process#379]
Hi all,

I have added LaurentRDC to the members of the org, and would like to get someone to add him to the hackage maintainers list so that he can maintain and manage releases. Unfortunately I am far out of the loop on this now, and cannot assist, but I think we can all agree that having another active maintainer is a good thing. 

Cheers,
Tim

**Comment by LaurentRDC** [comment]
Done, thanks!

**Comment by hyperthunk** [comment]
Hi Laurent,

Could we have a look at
https://github.com/hyperthunk/distributed-process-systest/issues/2 and
allocate hackage permissions so that those fixes can be done and
systest/async updates made on hackage please?

Kind regards,
Tim Watson

**Comment by LaurentRDC** [comment]
I see that you are the only one with upload permissions on Hackage.

If you forgot your password, I can contact the Hackage Trustees to add me and @davidsd as maintainers
