### ISSUE TITLE
Meta: merging most `haskell-distributed` repos into one

### ISSUE THREAD

**Issue by LaurentRDC** [haskell-distributed/distributed-process#382]
Dear @haskell-distributed/maintainers,

I would like to streamline maintenance of packages in this organization by merging most repositories into one. This will help keep all dependencies up-to-date, run cross-cutting tests, etc.

`cabal` has great support for multiple packages per repository; I have been working on Haskell monorepos for a few years and I love it.

Any thoughts or objections?

**Comment by LaurentRDC** [comment]
There is a [mechanism to transfer issues between repositories](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository)

**Comment by LaurentRDC** [comment]
@edsko Would you be able to make me and @davidsd owners of the organization?

This is required to change repository settings (e.g. description, archiving) and create new repositories

**Comment by LaurentRDC** [comment]
Calling on other organization owners: @hyperthunk @dcoutts @mboes 

Would you be able to make me and @davidsd owners of the organization?

This is required to change repository settings (e.g. description, archiving) and create new repositories

**Comment by mboes** [comment]
This is fine by me but I would prefer that someone from Well-Typed (@edsko @dcoutts or anyone else), i.e. the original authors, weigh in here before taking any action.

**Comment by edsko** [comment]
> Would you be able to make me and @davidsd owners of the organization?

After discussing this with Duncan, and given that Mathieu didn't object, I've made the both of you owner of the organization. 

I don't have any objections to this being a monorepo (I'm barely involved at all right now of course).

**Comment by LaurentRDC** [comment]
Thank you so much everyone!

**Comment by joelmccracken** [comment]
I'm super glad to see more movement on this project; thank you all for your work on this, and thank you to the new maintainers who have actually been moving things forward!

**Comment by chreekat** [comment]
@LaurentRDC which repo shall become *the* repo? This one, I suppose? I want to know which one to follow. :)

**Comment by LaurentRDC** [comment]
@chreekat this repo here would become _the_ repo. It has the most visibility already

**Comment by haroldcarr** [comment]
I'm curious.  I thought this project was dead.
Could you perhaps post in https://discourse.haskell.org/ what the status is and motivation for reviving it?  Whatever info you could give would be helpful to understand if one wants to contribute to this effort.

**Comment by davidsd** [comment]
Hi @haroldcarr at least a few of us have continued to use `distributed-process` productively for a long time. There was a period of a few years when it was not being kept up-to-date on hackage because the original maintainers had mostly moved on to other things. In the last couple years, @LaurentRDC and I received maintainer permissions and have been trying to keep things up-to-date.

**Comment by LaurentRDC** [comment]
Indeed, this project has remained functional for years thanks to @davidsd , and I started getting involved in the past year.

I posted on Discouse my personal reasons for getting involved. In short: I think this is cool technology, so much so that I am now using it at work.

**Comment by haroldcarr** [comment]
@davidsd @LaurentRDC Thank you for your response and the discourse post.
If I ever have some spare time you might see me pop up.
Thanks for your work.

**Comment by LaurentRDC** [comment]
Alternatively, could @facundominguez or @hyperthunk be able to help with giving publishing rights to the packages in the comment above?

**Comment by LaurentRDC** [comment]
@mboes Thank you so much!

This concludes the merging of the fundamental packages into this repo, and a micro version release on all of them.
