### ISSUE TITLE
Support containers 0.7 in network-transport-tests

### ISSUE THREAD

**Issue by davidsd** [haskell-distributed/distributed-process#457]
See https://github.com/commercialhaskell/stackage/issues/7549

**Comment by LaurentRDC** [comment]
Tested locally using `cabal test network-transport-inmemory --constraint="containers^>=0.7"` (`network-transport-inmemory` tests use `network-transport-tests`) with success

**Comment by LaurentRDC** [comment]
New revision published on Hackage

**Comment by davidsd** [comment]
Awesome -- thanks for the quick fix!
