### ISSUE TITLE
remove rematch dependency or take over rematch?

### ISSUE THREAD

**Issue by davidsd** [haskell-distributed/distributed-process#458]
Currently, I cannot add the following packages to stackage because they depend on `rematch` (which is not on stackage):

- distributed-process-systest
- distributed-process-extras
- distributed-process-async
- distributed-process-client-server
- distributed-process-supervisor
- distributed-process-execution

The `rematch` package was last updated in 2013 and does not appear to have a repo online anywhere. It is a very simple testing framework with only a couple hundred lines of code. We could:

- Try to contact the owner of `rematch` and either
   - Get him to add it to stackage, or
   - Transfer maintainership to us (which perhaps means including it in this repo), or
- Replace the dependency on rematch with a more widely used testing framework.

Thoughts?

**Comment by LaurentRDC** [comment]
I'm partial to removing the dependency on `rematch`, rather than taking it over.

I'm happy to create a patch. I can probably get this done in the next few days.

**Comment by davidsd** [comment]
Great!
