### ISSUE TITLE
Meta package to install all the other packages?

### ISSUE THREAD

**Issue by rodlogic** [haskell-distributed/distributed-process#60]
I had some issues where cabal had installed more than one version of these packages and apps were compiled using a mix of versions. Wondering if having a meta package (no code) that includes the other ones will help managing this.

I had to do something like this to get out of the cabal mess:
```sh
ghc-pkg list | grep -e distributed -e network-transport | xargs -t -I pkg ghc-pkg unregister pkg --force
```
And then reinstall the packages.

Maybe the following is already a good way?

```shell
cabal install distributed-process-simplelocalnet
```

**Comment by qnikst** [comment]
Now we have `cloud-haskell` package, however unregistering still will be a pain unless you use `sandboxes` or `stack` that could help will issues.
